version: "3"
services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:4000"
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true # 중요!! 리액트 핫 리로딩 적용. 윈도우 터미널에서 필요
    stdin_open: true # 리액트 한정 리액트 종료할때 필요

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
  # test 파일이 없어서 안됨
  # tests: 
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:4000"
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./frontend:/usr/src/app
  #   command: ["npm", "run", "test"]