version: "3"
services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:4000"
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
