version: 3
services:
  react:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "3000:4000"
    volumes:
      - /usr/src/app/node_modules
      - ./:usr/src/app
    stdin_open: true
