name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upgrade npm
      - run: npm install -g npm@9.8.1

      - name: Build the Docker image
      - run: docker-compose up --build
